name: "test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-unix:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    steps:
      # check-out repo and install python
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
      - name: Install dependencies
        run: pip install ".[dev,all]"
      - name: Run pytests
        run: python -m pytest --verbose tests

  test-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
      - name: Install dependencies
        run: pip install ".[dev,all]"
      - name: Run pytests
        run: python -m pytest --verbose tests
